apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "waas-gp-mvp"
spec:
  title: "Workshop"
  description: "Workshop description."
  publish:
    image: "$(image_repository)/waas-gp-mvp-files:$(workshop_version)"
  workshop:
    image: conda-environment:*
    files:
    - image:
        url: "$(image_repository)/waas-gp-mvp-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
    ingresses:
    - name: jupyter
      port: 8888
    dashboards:
    - name: Jupyter
      url: "$(ingress_protocol)://jupyter-$(session_name).$(ingress_domain)/"

# Reference for env vars: https://docs.educates.dev/custom-resources/workshop-definition#setting-environment-variables

# Extension packages: https://docs.educates.dev/custom-resources/workshop-definition#adding-extension-packages

